from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from sqlalchemy.orm import Session
from sqlalchemy import text
from backend.database import get_db
from backend.routers.auth import get_current_user
from backend import schemas
from backend import models # 🎯 NEW: Imported models for ORM

# REAL EMAIL MODULE IMPORT
from backend.email_service import send_notification_email
from backend.services.user_service import get_recipient_emails

router = APIRouter(prefix="/workflow", tags=["Workflow Actions"])

# --- EMAIL NOTIFICATION HELPER ---
def trigger_workflow_email(db: Session, request_id: int, target_stage: str, action_type: str, note: str, plant_id: str):
    """
    Looks up the target recipient's emails dynamically from the database 
    and sends a live HTML notification email via the network runner.
    """
    try:
        target_emails = []
        
        # Scenario A: Rejections or corrections targeting the specific original Creator
        if action_type == "REJECT" or target_stage == "Creator":
            # 🎯 FIX: Converted raw SQL JOIN to ORM
            result = db.query(models.User.email).join(
                models.MaterialRequest, models.User.user_id == models.MaterialRequest.created_by
            ).filter(
                models.MaterialRequest.request_id == request_id
            ).first()
            
            if result:
                target_emails = [result.email]

        # Let user_service.py handle Scenarios B, C, D, and E automatically!
        else:
            target_emails = get_recipient_emails(db, role=target_stage, plant_id=plant_id)

        # Live Execution Handshake Trigger
        if target_emails:
            # Determine appropriate subject line branding context
            subject_action = "Rejected" if action_type == "REJECT" else "Correction Required"
            title_color = "#C0392B" if action_type == "REJECT" else "#E67E22"
            
            # Generate uniform notification UI layout markup
            email_html = f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; border: 1px solid #e0e0e0; padding: 20px; border-radius: 8px;">
                <h3 style="color: {title_color}; margin-top: 0;">⚠️ Action Notice: Request Update</h3>
                <p>Hello,</p>
                <p>Material Request <strong>#{request_id}</strong> has been processed with action state <strong>{action_type}</strong> and routed to the <strong>{target_stage}</strong> workspace queue.</p>
                
                <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid {title_color}; margin: 15px 0;">
                    <strong>Reviewer Comments & Instructions:</strong><br/>
                    <span style="color: #555; font-style: italic;">"{note}"</span>
                </div>
                
                <p>Please log in to the <a href="http://127.0.0.1:8000/dashboard" style="color: #2980b9; text-decoration: none; font-weight: bold;">Viraj MDM Portal</a> to review this tracking row item.</p>
                <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;"/>
                <p style="font-size: 11px; color: #999; margin-bottom: 0;">This is an automated operational alert generated by the Viraj MDM Portal Workflow Engine.</p>
            </div>
            """
            
            # Loop through the list to broadcast the email
            for email in target_emails:
                send_notification_email(
                    to_email=email,
                    subject=f"Viraj MDM Portal: Request #{request_id} ({subject_action})",
                    html_content=email_html
                )
                print(f"\n[EMAIL SENT SUCCESS] Real message packet dispatched to: {email} | Action: {action_type}\n")
        else:
            print(f"\n[EMAIL WARNING] Target emails not found for Stage: {target_stage}\n")

    except Exception as e:
        print(f"Failed to process background email fetch: {str(e)}")


# --- WORKFLOW ENDPOINTS ---

@router.post("/{request_id}/reject")
def reject_request(
    request_id: int, 
    payload: schemas.ActionNote, 
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    current_user: dict = Depends(get_current_user)
):
    safe_username = current_user.get("username", f"User_{current_user.get('user_id')}")

    # 🎯 FIX: Fetch using ORM
    req_to_update = db.query(models.MaterialRequest).filter(models.MaterialRequest.request_id == request_id).first()
    
    if not req_to_update:
        raise HTTPException(status_code=404, detail="Request not found")

    try:
        # 🎯 FIX: Update global tracking state to 'Rejected' via ORM attributes
        req_to_update.status = 'Rejected'
        req_to_update.latest_note = payload.note
        req_to_update.return_to_stage = None

        # 🎯 FIX: Updated Audit Trail via ORM
        new_log = models.WorkflowLog(
            request_id=request_id,
            action_by=current_user.get("user_id"),
            username=safe_username,
            action_type='REJECTED',
            comments=payload.note
        )
        db.add(new_log)
        db.commit()
        
        # Process email alert non-blockingly via background thread
        background_tasks.add_task(
            trigger_workflow_email, 
            db=db, request_id=request_id, target_stage="Terminal", action_type="REJECT", note=payload.note, plant_id=req_to_update.plant_id
        )
        
        return {"message": "Request permanently rejected and notifier triggered."}
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Database Error: {str(e)}")


@router.post("/{request_id}/send-correction")
def send_for_correction(
    request_id: int, 
    payload: schemas.ActionNote, 
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    current_user: dict = Depends(get_current_user)
):
    safe_username = current_user.get("username", f"User_{current_user.get('user_id')}")

    # 🎯 FIX: Fetch live positional data via ORM
    req_to_update = db.query(models.MaterialRequest).filter(models.MaterialRequest.request_id == request_id).first()
    
    if not req_to_update:
        raise HTTPException(status_code=404, detail="Request not found")

    try:
        # Capture the specific stage that caught the error
        flagging_stage = req_to_update.current_stage
                
        # 🎯 FIX: OVERRIDE ROUTING via ORM attributes
        req_to_update.current_stage = 'Creator'
        req_to_update.status = 'Active'
        req_to_update.return_to_stage = flagging_stage
        req_to_update.latest_note = payload.note
        
        # 🎯 FIX: Updated Audit Trail via ORM
        new_log = models.WorkflowLog(
            request_id=request_id,
            action_by=current_user.get("user_id"),
            username=safe_username,
            action_type='RETURNED',
            comments=f"Returned by {flagging_stage}: {payload.note}" # Embedding the stage into the comment
        )
        db.add(new_log)
        db.commit()
        
        # Trigger email alert directly to the Creator
        background_tasks.add_task(
            trigger_workflow_email, 
            db=db, 
            request_id=request_id, 
            target_stage="Creator", 
            action_type="CORRECTION", 
            note=payload.note, 
            plant_id=req_to_update.plant_id
        )
        
        return {"message": f"Directly routed back to Creator. Once fixed, it will auto-return to {flagging_stage}."}
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Database Error: {str(e)}")